debug = false
destination = "personalcapital"
priceData = "coinbase"
destinationCurrencyAs = "USD"
[holdings]
    [holdings.coinbase]
    apiKey = "your-key"
    apiSecret = "your-secret"
    debug = false
[destinations]
    [destinations.personalcapital]
    email = "example@email.com"
    password = "password"
    accountName = "CryptoSync managed automatically"