openapi: 3.0.0
info:
  title: CoinBase API
  description: |
    Coinbase provides a simple and powerful REST API to integrate bitcoin, bitcoin cash, litecoin and ethereum payments into your business or application.

    This API reference provides information on available endpoints and how to interact with it. To read more about the API, visit our API documentation.
  version: 2019-11-15
servers:
  - url: https://api.coinbase.com/v2
    description: Coinbases Production Server
paths:
  /user:
    get:
      security:
        - ApiKeyAuth: ["wallet:user:read"]
      tags:
        - users
      summary: Show current user
      operationId: CurrentUser
      description: |
        Get current user’s public information. To get user’s email or private information, use permissions wallet:user:email and wallet:user:read. If current request has a wallet:transactions:send scope, then the response will contain a boolean sends_disabled field that indicates if the user’s send functionality has been disabled.
      parameters:
        - $ref: '#/components/parameters/CB-ACCESS-SIGN'
        - $ref: '#/components/parameters/CB-ACCESS-TIMESTAMP'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /accounts:
    get:
      security:
        - ApiKeyAuth: ["wallet:accounts:read"]
      tags:
        - accounts
      summary: List Accounts
      operationId: ListAccounts
      description: Lists current user’s accounts to which the authentication method has access to.
      parameters:
        - $ref: '#/components/parameters/CB-ACCESS-SIGN'
        - $ref: '#/components/parameters/CB-ACCESS-TIMESTAMP'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
  /accounts/{account_id}:
    get:
      security:
        - ApiKeyAuth: ["wallet:accounts:read"]
      tags:
        - accounts
      summary: Retrieve Account
      operationId: GetAccount
      description: Show current user’s account. To access the primary account for a given currency, a currency string (BTC or ETH) can be used instead of the account id in the URL.
      parameters:
        - $ref: '#/components/parameters/CB-ACCESS-SIGN'
        - $ref: '#/components/parameters/CB-ACCESS-TIMESTAMP'
        - in: path
          name: account_id   # Note the name is the same as in the path
          required: true
          schema:
            type: string
          description: The id of the account
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '401':
          $ref: '#/components/responses/ErrorMessage'
components:
  parameters:
    CB-ACCESS-SIGN:
      in: header
      name: CB-ACCESS-SIGN
      required: false
      description: |
        The user generated message signature (see below)
        The CB-ACCESS-SIGN header is generated by creating a sha256 HMAC using the secret key on the prehash string timestamp + method + requestPath + body (where + represents string concatenation).
      schema:
        type: string
        default: auto
      x-go-default-value: "auto"
      x-go-default: true
    CB-ACCESS-TIMESTAMP:
      in: header
      required: false
      name: CB-ACCESS-TIMESTAMP
      description: A timestamp for your request
      schema:
        type: integer
        default: auto
      x-go-default-value: "auto"
      x-go-default: true
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: CB-ACCESS-KEY
  responses:
    RateLimiting:
      description: being rate limited
    ErrorMessage:
      description: invalid token being used
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    pagination:
      type: object
      properties:
        ending_before:
          type: string
        starting_after:
          type: string
        limit:
          type: number
          minimum: 0
          maximum: 0
          default: 25
        order:
          enum: ["desc", "asc"]
          default: "desc"
        previous_uri:
          type: string
        next_uri:
          type: string
    Account:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        primary:
          type: boolean
        type:
          type: string
        currency:
          type: string
        balance:
          type: object
          properties:
            amount:
              type: string
            currency:
              type: string
          required:
            - amount
            - currency
        created_at:
          type: string
        updated_at:
          type: string
        resource:
          type: string
        resource_path:
          type: string
        ready:
          type: boolean
      required:
        - id
        - name
        - primary
        - type
        - currency
        - balance
        - created_at
        - updated_at
        - resource
        - resource_path
        - ready
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              message:
                type: string
            required:
              - id
              - message
      required:
        - errors
    User:
      type:
        object
      properties:
        id:
          type: string
        name:
          type: string
        username:
          type: string
        profile_location:
          type: string
        profile_bio:
          type: string
        profile_url:
          type: string
        avatar_url:
          type: string
        resource:
          type: string
        resource_path:
          type: string
